# Form implementation generated from reading ui file 'maindashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import darkdetect
import os
from PyQt6.QtGui import QIcon
from PyQt6 import QtCore, QtGui, QtWidgets
import MySQLdb as mysql_db

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 121, 16))
        self.label.setObjectName("label")
        self.stock_list = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.stock_list.setGeometry(QtCore.QRect(50, 40, 441, 131))
        self.stock_list.setObjectName("stock_list")
        self.stock_detail = QtWidgets.QPushButton(parent=self.stock_list)
        self.stock_detail.setGeometry(QtCore.QRect(360, 100, 75, 23))
        self.stock_detail.setObjectName("stock_detail")
        self.invoice_daily = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.invoice_daily.setGeometry(QtCore.QRect(50, 180, 441, 131))
        self.invoice_daily.setObjectName("invoice_daily")
        self.invoice_detail = QtWidgets.QPushButton(parent=self.invoice_daily)
        self.invoice_detail.setGeometry(QtCore.QRect(360, 100, 75, 23))
        self.invoice_detail.setObjectName("invoice_detail")
        self.list_outdate = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.list_outdate.setGeometry(QtCore.QRect(50, 320, 441, 131))
        self.list_outdate.setObjectName("list_outdate")
        self.warning_detail = QtWidgets.QPushButton(parent=self.list_outdate)
        self.warning_detail.setGeometry(QtCore.QRect(360, 100, 75, 23))
        self.warning_detail.setObjectName("warning_detail")
        self.invoice_create = QtWidgets.QPushButton(parent=self.centralwidget)
        self.invoice_create.setGeometry(QtCore.QRect(390, 460, 101, 23))
        self.invoice_create.setObjectName("invoice_create")
        self.general_mana = QtWidgets.QPushButton(parent=self.centralwidget)
        self.general_mana.setGeometry(QtCore.QRect(50, 460, 101, 23))
        self.general_mana.setObjectName("general_mana")
        self.export_report = QtWidgets.QPushButton(parent=self.centralwidget)
        self.export_report.setGeometry(QtCore.QRect(160, 460, 71, 23))
        self.export_report.setObjectName("export_report")
        self.drug_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.drug_add.setGeometry(QtCore.QRect(240, 460, 81, 23))
        self.drug_add.setObjectName("drug_add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#  added function
        self.drug_add.clicked.connect(self.db_connect)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MediManager"))
        self.label.setText(_translate("MainWindow", "MediManager"))
        self.stock_list.setTitle(_translate("MainWindow", "DANH SÁCH THUỐC TỒN KHO"))
        self.stock_detail.setText(_translate("MainWindow", "CHI TIẾT"))
        self.invoice_daily.setTitle(_translate("MainWindow", "DANH SÁCH HÓA ĐƠN TRONG NGÀY"))
        self.invoice_detail.setText(_translate("MainWindow", "CHI TIẾT"))
        self.list_outdate.setTitle(_translate("MainWindow", "THUỐC SẮP HẾT HẠN"))
        self.warning_detail.setText(_translate("MainWindow", "CHI TIẾT"))
        self.invoice_create.setText(_translate("MainWindow", "TẠO HÓA ĐƠN"))
        self.general_mana.setText(_translate("MainWindow", "QUẢN LÝ CHUNG"))
        self.export_report.setText(_translate("MainWindow", "IN BÁO CÁO"))
        self.drug_add.setText(_translate("MainWindow", "THÊM THUỐC"))

    def db_connect(self):
        db=mysql_db.connect('localhost','root','@Thanh070891','medimanager')
        # try:
        #     db=mysql_db.connect('localhost','root','@Thanh070891','medimanager')
        #     msg=QtWidgets.QMessageBox()
        #     msg.setInformativeText('Connect Success')
        #     msg.exec()
        # except:
        #     msg=QtWidgets.QMessageBox()
        #     msg.setInformativeText('Connect Failed')
        #     msg.exec()


                           
                           
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
