# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'medicine_information_add.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDateEdit,
    QDialog, QDialogButtonBox, QDoubleSpinBox, QLabel,
    QLineEdit, QSizePolicy, QSpinBox, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(335, 625)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(-20, 590, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Save)
        self.Name = QLabel(Dialog)
        self.Name.setObjectName(u"Name")
        self.Name.setGeometry(QRect(20, 320, 61, 21))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 321, 20))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.Image = QLabel(Dialog)
        self.Image.setObjectName(u"Image")
        self.Image.setGeometry(QRect(30, 50, 251, 211))
        self.Image.setPixmap(QPixmap(u"../icon/medicine_icon.png"))
        self.Image.setScaledContents(True)
        self.Image.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 311, 261))
        self.label_5.setAutoFillBackground(True)
        self.Category = QLabel(Dialog)
        self.Category.setObjectName(u"Category")
        self.Category.setGeometry(QRect(20, 380, 61, 21))
        self.GenName = QLabel(Dialog)
        self.GenName.setObjectName(u"GenName")
        self.GenName.setGeometry(QRect(20, 350, 61, 21))
        self.BatchNo = QLabel(Dialog)
        self.BatchNo.setObjectName(u"BatchNo")
        self.BatchNo.setGeometry(QRect(20, 440, 61, 21))
        self.Supplier = QLabel(Dialog)
        self.Supplier.setObjectName(u"Supplier")
        self.Supplier.setGeometry(QRect(20, 410, 61, 21))
        self.medicine_name = QLineEdit(Dialog)
        self.medicine_name.setObjectName(u"medicine_name")
        self.medicine_name.setGeometry(QRect(100, 320, 221, 20))
        self.batch_number = QLineEdit(Dialog)
        self.batch_number.setObjectName(u"batch_number")
        self.batch_number.setGeometry(QRect(100, 440, 221, 20))
        self.generic_name = QLineEdit(Dialog)
        self.generic_name.setObjectName(u"generic_name")
        self.generic_name.setGeometry(QRect(100, 350, 221, 20))
        self.ExpDate = QLabel(Dialog)
        self.ExpDate.setObjectName(u"ExpDate")
        self.ExpDate.setGeometry(QRect(20, 470, 61, 21))
        self.UnitPrice = QLabel(Dialog)
        self.UnitPrice.setObjectName(u"UnitPrice")
        self.UnitPrice.setGeometry(QRect(20, 530, 61, 21))
        self.SalePrice = QLabel(Dialog)
        self.SalePrice.setObjectName(u"SalePrice")
        self.SalePrice.setGeometry(QRect(20, 560, 61, 21))
        self.Quantity = QLabel(Dialog)
        self.Quantity.setObjectName(u"Quantity")
        self.Quantity.setGeometry(QRect(20, 500, 61, 21))
        self.Image_2 = QLabel(Dialog)
        self.Image_2.setObjectName(u"Image_2")
        self.Image_2.setGeometry(QRect(40, 50, 251, 211))
        self.Image_2.setPixmap(QPixmap(u"../icon/medicine_icon.png"))
        self.Image_2.setScaledContents(True)
        self.Image_2.setAlignment(Qt.AlignCenter)
        self.comboBox = QComboBox(Dialog)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(100, 380, 221, 22))
        self.comboBox_2 = QComboBox(Dialog)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(100, 410, 221, 22))
        self.dateEdit = QDateEdit(Dialog)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(100, 470, 221, 22))
        self.spinBox = QSpinBox(Dialog)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(100, 500, 221, 22))
        self.doubleSpinBox = QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(100, 530, 221, 22))
        self.doubleSpinBox_2 = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(100, 560, 221, 22))
        self.label_5.raise_()
        self.buttonBox.raise_()
        self.Name.raise_()
        self.label_3.raise_()
        self.Image.raise_()
        self.Category.raise_()
        self.GenName.raise_()
        self.BatchNo.raise_()
        self.Supplier.raise_()
        self.medicine_name.raise_()
        self.batch_number.raise_()
        self.generic_name.raise_()
        self.ExpDate.raise_()
        self.UnitPrice.raise_()
        self.SalePrice.raise_()
        self.Quantity.raise_()
        self.Image_2.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.dateEdit.raise_()
        self.spinBox.raise_()
        self.doubleSpinBox.raise_()
        self.doubleSpinBox_2.raise_()
        QWidget.setTabOrder(self.medicine_name, self.batch_number)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.Name.setText(QCoreApplication.translate("Dialog", u"Name", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"ADD NEW MEDICINE", None))
        self.Image.setText("")
        self.label_5.setText("")
        self.Category.setText(QCoreApplication.translate("Dialog", u"Category", None))
        self.GenName.setText(QCoreApplication.translate("Dialog", u"Gen. Name", None))
        self.BatchNo.setText(QCoreApplication.translate("Dialog", u"Batch No.", None))
        self.Supplier.setText(QCoreApplication.translate("Dialog", u"Supplier", None))
        self.ExpDate.setText(QCoreApplication.translate("Dialog", u"Exp. Date", None))
        self.UnitPrice.setText(QCoreApplication.translate("Dialog", u"Unit Price", None))
        self.SalePrice.setText(QCoreApplication.translate("Dialog", u"Sale Price", None))
        self.Quantity.setText(QCoreApplication.translate("Dialog", u"Quantity", None))
        self.Image_2.setText("")
    # retranslateUi

