# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_register_2(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(245, 152)
        self.centralwidget = QtWidgets.QWidget(parent=register_2)
        self.centralwidget.setObjectName("centralwidget")
        self.register_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(80, 80, 75, 23))
        self.register_button.setObjectName("register_button")
        self.register_user = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.register_user.setGeometry(QtCore.QRect(80, 20, 141, 20))
        self.register_user.setObjectName("register_user")
        self.user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(10, 20, 47, 14))
        self.user_label.setObjectName("user_label")
        self.register_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.register_password.setGeometry(QtCore.QRect(80, 50, 141, 20))
        self.register_password.setObjectName("register_password")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        register_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=register_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 245, 22))
        self.menubar.setObjectName("menubar")
        register_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=register_2)
        self.statusbar.setObjectName("statusbar")
        register_2.setStatusBar(self.statusbar)

        self.retranslateUi(register_2)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "MainWindow"))
        self.register_button.setText(_translate("register_2", "REGISTER"))
        self.register_user.setText(_translate("register_2", "enter username"))
        self.user_label.setText(_translate("register_2", "user"))
        self.register_password.setText(_translate("register_2", "enter password"))
        self.label_2.setText(_translate("register_2", "password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_2 = QtWidgets.QMainWindow()
    ui = Ui_register_2()
    ui.setupUi(register_2)
    register_2.show()
    sys.exit(app.exec())
