# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'supplier_information.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDialog,
    QDialogButtonBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTextEdit, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(335, 610)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(-20, 571, 341, 31))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Close)
        self.ID = QLabel(Dialog)
        self.ID.setObjectName(u"ID")
        self.ID.setGeometry(QRect(20, 323, 47, 16))
        self.Name = QLabel(Dialog)
        self.Name.setObjectName(u"Name")
        self.Name.setGeometry(QRect(20, 351, 47, 20))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 321, 20))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.Image = QLabel(Dialog)
        self.Image.setObjectName(u"Image")
        self.Image.setGeometry(QRect(30, 50, 251, 211))
        self.Image.setPixmap(QPixmap(u"../icon/supplier_icon.png"))
        self.Image.setScaledContents(True)
        self.Image.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 311, 261))
        self.label_5.setAutoFillBackground(True)
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 434, 47, 16))
        self.Address = QLabel(Dialog)
        self.Address.setObjectName(u"Address")
        self.Address.setGeometry(QRect(20, 380, 47, 21))
        self.Phone = QLabel(Dialog)
        self.Phone.setObjectName(u"Phone")
        self.Phone.setGeometry(QRect(20, 464, 47, 16))
        self.Email = QLabel(Dialog)
        self.Email.setObjectName(u"Email")
        self.Email.setGeometry(QRect(20, 491, 47, 20))
        self.supplier_address = QTextEdit(Dialog)
        self.supplier_address.setObjectName(u"supplier_address")
        self.supplier_address.setGeometry(QRect(80, 380, 241, 41))
        self.supplier_id = QLineEdit(Dialog)
        self.supplier_id.setObjectName(u"supplier_id")
        self.supplier_id.setGeometry(QRect(80, 320, 241, 20))
        self.supplier_name = QLineEdit(Dialog)
        self.supplier_name.setObjectName(u"supplier_name")
        self.supplier_name.setGeometry(QRect(80, 350, 241, 20))
        self.contact_name = QLineEdit(Dialog)
        self.contact_name.setObjectName(u"contact_name")
        self.contact_name.setGeometry(QRect(80, 430, 241, 20))
        self.contact_phone = QLineEdit(Dialog)
        self.contact_phone.setObjectName(u"contact_phone")
        self.contact_phone.setGeometry(QRect(80, 460, 241, 20))
        self.contact_email = QLineEdit(Dialog)
        self.contact_email.setObjectName(u"contact_email")
        self.contact_email.setGeometry(QRect(80, 490, 241, 20))
        self.Payment = QLabel(Dialog)
        self.Payment.setObjectName(u"Payment")
        self.Payment.setEnabled(True)
        self.Payment.setGeometry(QRect(20, 521, 47, 20))
        self.comboBox_payment_terms = QComboBox(Dialog)
        self.comboBox_payment_terms.addItem("")
        self.comboBox_payment_terms.addItem("")
        self.comboBox_payment_terms.setObjectName(u"comboBox_payment_terms")
        self.comboBox_payment_terms.setEnabled(True)
        self.comboBox_payment_terms.setGeometry(QRect(80, 520, 241, 22))
        self.comboBox_payment_terms.setEditable(False)
        self.comboBox_payment_terms.setMaxVisibleItems(2)
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(80, 290, 61, 21))
        self.label_5.raise_()
        self.buttonBox.raise_()
        self.ID.raise_()
        self.Name.raise_()
        self.label_3.raise_()
        self.Image.raise_()
        self.label_6.raise_()
        self.Address.raise_()
        self.Phone.raise_()
        self.Email.raise_()
        self.supplier_address.raise_()
        self.supplier_id.raise_()
        self.supplier_name.raise_()
        self.contact_name.raise_()
        self.contact_phone.raise_()
        self.contact_email.raise_()
        self.Payment.raise_()
        self.comboBox_payment_terms.raise_()
        self.pushButton.raise_()
        QWidget.setTabOrder(self.supplier_id, self.supplier_name)
        QWidget.setTabOrder(self.supplier_name, self.supplier_address)
        QWidget.setTabOrder(self.supplier_address, self.contact_name)
        QWidget.setTabOrder(self.contact_name, self.contact_phone)
        QWidget.setTabOrder(self.contact_phone, self.contact_email)
        QWidget.setTabOrder(self.contact_email, self.comboBox_payment_terms)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.ID.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.Name.setText(QCoreApplication.translate("Dialog", u"Name", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"SUPPLIER INFORMATION", None))
        self.Image.setText("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Contact", None))
        self.Address.setText(QCoreApplication.translate("Dialog", u"Address", None))
        self.Phone.setText(QCoreApplication.translate("Dialog", u"Phone", None))
        self.Email.setText(QCoreApplication.translate("Dialog", u"Email", None))
#if QT_CONFIG(tooltip)
        self.Payment.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.Payment.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.Payment.setText(QCoreApplication.translate("Dialog", u"Payment", None))
        self.comboBox_payment_terms.setItemText(0, QCoreApplication.translate("Dialog", u"COD", None))
        self.comboBox_payment_terms.setItemText(1, QCoreApplication.translate("Dialog", u"prepayment", None))

        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Edit...", None))
    # retranslateUi

